2025-06-08 10:27:13,771 INFO    MainThread:2012682 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-06-08 10:27:13,771 INFO    MainThread:2012682 [wandb_setup.py:_flush():70] Configure stats pid to 2012682
2025-06-08 10:27:13,771 INFO    MainThread:2012682 [wandb_setup.py:_flush():70] Loading settings from /home/vcivale/.config/wandb/settings
2025-06-08 10:27:13,771 INFO    MainThread:2012682 [wandb_setup.py:_flush():70] Loading settings from /home/vcivale/prova/Esercitazione_2/wandb/settings
2025-06-08 10:27:13,771 INFO    MainThread:2012682 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-06-08 10:27:13,772 INFO    MainThread:2012682 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/vcivale/prova/Esercitazione_2/wandb/run-20250608_102713-yajak0zj/logs/debug.log
2025-06-08 10:27:13,772 INFO    MainThread:2012682 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/vcivale/prova/Esercitazione_2/wandb/run-20250608_102713-yajak0zj/logs/debug-internal.log
2025-06-08 10:27:13,772 INFO    MainThread:2012682 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f65cbf13820>
2025-06-08 10:27:13,772 INFO    MainThread:2012682 [wandb_init.py:init():852] calling init triggers
2025-06-08 10:27:13,773 INFO    MainThread:2012682 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'checkpoint': 0, 'test': False, 'trial': 5, 'wandb_project': 'CarRacing-v0-PPO', 'start_episode': 0, 'gamma': 0.99, 'clip_param': 0.4, 'ppo_epoch': 10, 'buffer_capacity': 500, 'batch_size': 128, 'seed': 0, 'action_repeat': 4, 'deathThreshold': 2000, 'deathByGreeneryThreshold': 35, 'maxDistance': 100, 'max_episode_steps': 10000, 'valueStackSize': 8, 'actionStack': 0, 'numberOfLasers': 5, 'actionMultiplier': [2.0, 1.0, 1.0], 'actionBias': [-1.0, 0.0, 0.0], 'saveLocation': 'model/distances/train_5/', '_wandb': {}}
2025-06-08 10:27:13,773 INFO    MainThread:2012682 [wandb_init.py:init():893] starting backend
2025-06-08 10:27:13,773 INFO    MainThread:2012682 [wandb_init.py:init():897] sending inform_init request
2025-06-08 10:27:13,777 INFO    MainThread:2012682 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-06-08 10:27:13,777 INFO    MainThread:2012682 [wandb_init.py:init():907] backend started and connected
2025-06-08 10:27:13,789 INFO    MainThread:2012682 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-06-08 10:27:13,791 INFO    MainThread:2012682 [wandb_init.py:init():1005] updated telemetry
2025-06-08 10:27:13,801 INFO    MainThread:2012682 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-06-08 10:27:14,338 INFO    MainThread:2012682 [wandb_init.py:init():1104] starting run threads in backend
2025-06-08 10:27:14,609 INFO    MainThread:2012682 [wandb_run.py:_console_start():2573] atexit reg
2025-06-08 10:27:14,610 INFO    MainThread:2012682 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-06-08 10:27:14,610 INFO    MainThread:2012682 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-06-08 10:27:14,611 INFO    MainThread:2012682 [wandb_run.py:_redirect():2513] Redirects installed.
2025-06-08 10:27:14,613 INFO    MainThread:2012682 [wandb_init.py:init():1150] run started, returning control to user process
2025-06-08 10:27:15,339 INFO    MainThread:2012682 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-08 10:27:23,078 WARNING MsgRouterThr:2012682 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-08 10:27:23,079 INFO    MsgRouterThr:2012682 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
