2025-06-08 10:04:18,544 INFO    MainThread:2008282 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/vcivale/prova/Esercitazione_2/wandb/run-20250608_100418-zdtk33ap/logs/debug.log
2025-06-08 10:04:18,544 INFO    MainThread:2008282 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/vcivale/prova/Esercitazione_2/wandb/run-20250608_100418-zdtk33ap/logs/debug-internal.log
2025-06-08 10:04:18,544 INFO    MainThread:2008282 [wandb_init.py:init():852] calling init triggers
2025-06-08 10:04:18,544 INFO    MainThread:2008282 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'gamma': 0.99, 'clip_param': 0.2, 'buffer_capacity': 1000, 'batch_size': 32, 'ppo_epoch': 10, 'max_episodes': 2000, 'action_repeat': 4, 'device': 'cuda:0', '_wandb': {}}
2025-06-08 10:04:19,650 INFO    MainThread:2008282 [wandb_init.py:init():893] starting backend
2025-06-08 10:04:19,650 INFO    MainThread:2008282 [wandb_init.py:init():897] sending inform_init request
2025-06-08 10:04:19,652 INFO    MainThread:2008282 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-06-08 10:04:19,652 INFO    MainThread:2008282 [wandb_init.py:init():907] backend started and connected
2025-06-08 10:04:19,665 INFO    MainThread:2008282 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-06-08 10:04:19,667 INFO    MainThread:2008282 [wandb_init.py:init():1005] updated telemetry
2025-06-08 10:04:19,678 INFO    MainThread:2008282 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-06-08 10:04:20,252 INFO    MainThread:2008282 [wandb_init.py:init():1104] starting run threads in backend
2025-06-08 10:04:20,526 INFO    MainThread:2008282 [wandb_run.py:_console_start():2573] atexit reg
2025-06-08 10:04:20,526 INFO    MainThread:2008282 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-06-08 10:04:20,526 INFO    MainThread:2008282 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-06-08 10:04:20,526 INFO    MainThread:2008282 [wandb_run.py:_redirect():2513] Redirects installed.
2025-06-08 10:04:20,527 INFO    MainThread:2008282 [wandb_init.py:init():1150] run started, returning control to user process
2025-06-08 10:15:28,142 WARNING MsgRouterThr:2008282 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/vcivale/prova/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-08 10:15:28,159 INFO    MsgRouterThr:2008282 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
